### ISSUE TITLE
Small issues with Social Interaction interface

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#63]
I have implemented the Twitter and Facebook Social Interaction services into my apps and found a number of issues. 1. and 2. are small but 3. is of greater concern:

1. The Twitter Post Image function left the message empty when cast to Social but worked correctly when cast to Twitter. In both cases the image was correctly included.

2. I had initial difficulties with logout. I want to be able to logout to enable login as a different user or, in the case of Facebook, with different settings. I eventually found the answer in your FAQ but I only found to through an internet search throwing up the last FAQ. This is that you also need to flush the cookies from the web view. Might it be possible to build in some sort of cross-reference or to include more in the function documentation?

3. Using logout, saving credentials as an empty string and flushing cookies resolved my issues and correctly forced re-login with one exception. This is that for Facebook after the initial login screen. the second screen was not displayed, except when logging in for the very first time with an app. This is the screen where you set what data can be accessed, you enable posts of images (which are not enabled by default), and you indicate who can see the posts. Even when I re-installed my apps this screen did not reappear. This, to me, is a problem. There needs to be a way to re-visit these settings.

**Comment by PatrickStoklasa** [comment]
Hi Don,

1. Just to get his right, you tried posting the same message, once with a Twitter instance and once with the same instance but cast to Social? In one case it worked fine and in one it uploaded the image but didn't post the message?

2. We are currently doing a rework of the whole documentation and the portal such that it becomes easier to access. I believe that this will solve the problem.

3. I haven't tried that myself yet but i quickly scanned our implementation of the logout method. It seems that it calls the correct method on the Facebook API in order to completely revoke access. And if the method does not throw an error it should have done so. According to the Facebook documentation the user should see the same permission dialog as if the app has never had access before. I will validate the behavior myself and come back as soon as i have further information.

**Comment by donpwilson** [comment]
Patrick,

Re 1. Yes. Actually I started my implementation casting to Social and found that the message was missing. I then switched to using a cast to Twitter which worked so I never looked back.

Also, did you ever get a chance to look at interfacing to Google Photos as a variant of Google Drive? If not and you don’t think you’ll be able to do so, is there any way that I could experiment for you?

**Comment by PatrickStoklasa** [comment]
Re 1: I could not verify this behavior for me. All our tests work on an instance of Social and the post contain the correct message. Maybe you could try it again with casting to Social or if it works for you the way you have it right now just keep it.

Re 3: I have found an issue in the logout method and for me this solves the problem. So when i call login, logout and login again i will be correctly prompted with the screen that asks me for access. It is available in the new version i just released (v2.16.1).

Re Google Photos: I recalled one of our email conversations where you said that the only thing that is different is the scope requested during the authentication. We have lately added the option to exactly specify the scopes you want to obtain from the service. It is not yet documented in the current documentation but you can basically pass a list of strings (permissions) as a separate parameter to the constructor. You can try passing the one for Google Photos and see what happens. I would be curious to know.

**Comment by donpwilson** [comment]
Re 1: I cannot recreate this issue using v2.16.1. Please regard it as closed.

Re 3. I'm still getting the same behaviour with v 2.16.1. The second screen still doesn't appear. I've tested this using API 17 and API 25 to cover both methods of clearing cookies. I show below my code in case this might show up an issue. I use similar code for tweets. Note the absence of a "break" at the end of the first switch option:

```
case Dialog_Compose_Post.FACEBOOK_POST:
                    final Facebook facebook = new Facebook(My_Application_Base.getInstance().getApplicationContext(),
                            Get.GetString(R.string.facebook_app_id), Get.GetString(R.string.facebook_secret));
                    switch (click) {
                        case Dialog_Compose_Post.SEND_WITH_LOGIN:
                            facebook.logout();
                            clearWebViewCookies();
                            My_Preferences.getInstance().setCloudrailFacebookCredentials("");
                        case Dialog_Compose_Post.SEND:
                            String credentials = My_Preferences.getInstance().getCloudrailFacebookCredentials();
                            if (!credentials.equals("")) {
                                facebook.loadAsString(credentials);
                            }
                            if (!photo_records.isEmpty()) {
                                facebook.postImage(text, new FileContent("image/jpeg",
                                        new File(photo_records.get(0).getPhoto())).getInputStream());
                            } else {
                                facebook.postUpdate(text);
                            }
                            My_Preferences.getInstance().setCloudrailFacebookCredentials(facebook.saveAsString());
                            break;
                    }
                    break;
            }
            ```
`    @SuppressWarnings("deprecation")
    private void clearWebViewCookies() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            CookieSyncManager cookie_sync_manager = CookieSyncManager.createInstance(My_Application_Base
                    .getInstance().getApplicationContext());
            cookie_sync_manager.startSync();
            CookieManager cookieManager = CookieManager.getInstance();
            cookieManager.removeAllCookie();
            cookieManager.removeSessionCookie();
            cookie_sync_manager.stopSync();
            cookie_sync_manager.sync();
        } else {
            CookieManager.getInstance().removeAllCookies(null);
            CookieManager.getInstance().flush();
        }
    }
`
Re Google Photos: I can see the option to add scopes. However, there is one other change required. This is that functions that seek files need to know where to look. in the Google REST API this is covered by:
`setSpaces("drive")`
or:
`setSpaces("photos")`

This is referenced here [https://developers.google.com/drive/v3/reference/files/list](url). I suspect that you currently have "drive" effectively hard coded. I think it is the default if nothing specific is entered. I hope this helps. It would be great to get this working!

**Comment by PatrickStoklasa** [comment]
The code seems fine to me... In my test case i literally just called login(), logout() and login() one after the other without clearing the cookies. This didn't log me out of Facebook of course but i got the consent screen again. Maybe you could try just that and see if it works in general for you or if we might need to check the app configuration or the source code again. You are using the standard way of authentication i assume?

Re GooglePhotos: We don't have anything hard coded but i assume that the default then is 'drive'. Have you tried it? Maybe it uses 'photos' by default if the access token is scoped for it. But if this doesn't work the only other option would be to use the advanced request feature which will let you formulate requests by yourself by taking care of the authentication and error checking.

**Comment by donpwilson** [comment]
Posting a photo to Facebook is the only place where I use the Cloudrail Facebook service. My app also uses the Facebook SDK when the Facebook app is installed on the phone/tablet. To try to eliminate this as a cause of the issue I commented it out of my app and, on the Facebook developers portal, set up a new app to connect using Cloudrail following your instructions for the service. Initially I was using the same app for both interfaces. Even with this revised link I still had the same issue. I suppose it is possible that Facebook stores the permissions internally based on my app's package name and this is what it looks for before showing the permissions / consent screen.

To sum up, in all of my testing I've been able to force re-login but I've never had the screen that follows login except the first time I've logged in using a particular Facebook app with associated id and secret. This is the screen where the user selects who sees the post. It is followed by a further screen where the user agrees to allow images to be posted as this permission is not granted by default. Are you getting all 3 screens?

Re Google Photos, I had to specify "photos" specifically as the "space" to get the link working using the Google Drive REST Api. I'll give the advanced request feature a go. This may take a while because there's a lot I need to figure out. For instance, I haven't had to do much with JSON before now - one of the reasons for using Cloudrail.  "scopes" are associated with a function, not with authentication. My inclination is to work from your cloud file manager example to keep things as simple as possible. Is there any chance that you could provide an example of using the advanced request feature?

**Comment by PatrickStoklasa** [comment]
I haven't cleared cookies for my test so after calling logout i only get two screens. The one asking for general permissions and the other one for asking who is supposed to see posts from this app. I do have another idea of how you could find out if the logout works correctly. Facebook provides a method of checking the permissions of an access token. So here is what you can do:

First set a breakpoint right before calling logout and print the access token to the console. Open the Facebook Graph API Explorer (https://developers.facebook.com/tools/explorer) and select your app in the top right corner. Paste the access token printed by the app into the correct field and set the path to /me/permissions. The result of the call should be the list of all permissions. Now execute the logout and send the same request again. Now you should get an error like this:

    {
      "error": {
        "message": "Error validating access token: The user has not authorized application 1218944988167653.",
        "type": "OAuthException",
        "code": 190,
        "error_subcode": 458,
        "fbtrace_id": "H4FEQCPKi0A"
      }
    }

RE GooglePhotos: I guess in order to list photos you would want to do sth. like this:

    GoogleDrive gd = new GoogleDrive(/* Credentials and scope */);

    String path = "/files?spaces=photos";
    AdvancedRequestSpecification spec = new AdvancedRequestSpecification(path);
    spec.setMethod("GET"); // This line is even optional i think

    AdvancedRequestResponse res = gd.advancedRequest(spec);
    Map<String, Object> resObj = (Map<String, Object>) res.getBodyJsonParsed();
    // Work with the response

**Comment by donpwilson** [comment]
Re Facebook logout, I applied your test. Initially the logout did not work but the test made me realize that I hadn't loaded the credentials into the Facebook service instance. When I corrected this I got the consent screen. I'm still testing to make sure this is fully working but in the meantime thanks for pointing me in the right direction.

Re Google Photos, I've made steps towards this by implementing the Google Drive interface in my app using External Authentication. This is basically working now but I've hit a problem. I'm using getChildren() to download image files and they all appear to be found. However both CloudMetaData() and getModifiedAt() are returning null. 

The main problem is that getModifiedAt() is supposed to return a Long so it is not readily possible to test for null.

More generally, I note that there have been a number of issues raised in the past with null being returned for these items for Google Drive even though the data does actually exist. I couldn't quite see how exactly they were resolved.

**Comment by PatrickStoklasa** [comment]
Glad i could help!

Concerning the modified date: I checked our implementation again and in every spot where we create metadata objects we always check if the 'modifiedTime' is present within the response and if so we add it to the metadata. So if it is 0 then it wasn't returned by the API. Maybe you could try the call via Googles API Explorer at the bottom of each endpoint documentation and see if it is actually present.

Concerning getChildren(): What you are saying is that you get entries within the list that are null and not a valid CloudMetadata object at all? Or did i get that wrong?

**Comment by donpwilson** [comment]
One last (hopefully) Facebook service question as I can now confirm that logout / login appears to be working.

At the top of the second screen to appear there is a message from Facebook that I should "Submit for Login Review. Some of the permissions below have not been approved for use by Facebook.". 

When I investigate further by starting the process of submission, cannot work out what permissions I need to request in order to enable posting to Facebook - which is all that my app needs. As far as I can see, I don't want any of the long list that is presented and, indeed, want to disallow those that are enabled by default: your public profile, Friends list, email address, date of birth, photos and personal description."  However I cannot proceed without selecting at least one category.

Any thoughts? Have you come across this issue before?

Re Google Drive, I apologize - I meant ImageMetaData is null. not CloudMetaData. I know that modifiedDate is present because I download it using my current implementation using the REST API.

Re Google Photos, I'm making progress but only spasmodically. I've now got a basic Advanced Request working for Google Drive but switching the scope and spaces to Google Photos did not immediately work. I suggest that I open a separate issue for this if or when I need it as we have moved a long way off the original query.

**Comment by PatrickStoklasa** [comment]
As far as I know there are some permissions that are approved by default. So you don't need to request them if your app wants to use them. If you only want to use the permission for posting you can specify the scopes just like with Google Drive. The scope you are looking for is 'publish_actions' if i'm not mistaken.

RE Google Drive: Ok then i will need to see if i can reproduce it for myself. I will let you know when i have some more information.

RE Google Photos: Yes i think that makes sense.

**Comment by donpwilson** [comment]
Patrick, have you made any progress with the outstanding issue from the above correspondence. This is that, for Google Drive using getChildren() and interrogating the list of CloudMetaData objects, both getModifiedAt(0and getImageMetaData() return null. The other methods contain the correct values.

I know that the data exists server side because I can download it if I use an Advanced Request.  However I don't then get the path  - which I need for other methods. I have a workaround for getImageMetaData() because I have to download the image to obtain the additional image meta data that I need. However, I have not been able to find a workaround for getModifiedAt() which is a crucial field to check whether images have been changed.

**Comment by PatrickStoklasa** [comment]
I found the issue in the meantime. There will be another release over the weekend i assume. The fix will be included there. I will let you know when it is published.

**Comment by PatrickStoklasa** [comment]
The issue should now be covered with the new version 2.16.6. Just let me know if it works.

**Comment by donpwilson** [comment]
Partial success! 

service.getChildren() works but service.getChildrenPage() still returns null.

**Comment by PatrickStoklasa** [comment]
I have done the same changes to getChildrenPage now. Try the new version 2.17.0 and let me know if it works.

**Comment by donpwilson** [comment]
I'm sorry to have to report that I'm still getting null for both ImageMetaData and modifiedAt.

**Comment by PatrickStoklasa** [comment]
Now it should be fixed though

**Comment by donpwilson** [comment]
I changed my gradle reference to 2.17.1  and re-synced. I confirm that I am now getting valid values. I still need to do further testing but I thought I should let you know. Incidentally, your installation documentation still refers to 2.17.0. Intentionally?!

**Comment by PatrickStoklasa** [comment]
It was not intentionally, it should be updated now. Glad to hear that it works now! Just close this issue when you can confirm that it is working correctly.
